### ISSUE TITLE
Please use releases for releasing the nbm package

### ISSUE THREAD

**Issue by silkentrance** [tusharvjoshi/NBDrupalDevel#40]
Instead of providing the assembled nbm package in the repository, you should consider releasing them as a release, see https://github.com/HollyIT/NBDrupalDevel/releases.

**Comment by tusharvjoshi** [comment]
The binary file NBDrupalDevelTool.nbm is now removed from the source repository.  There is one release available for v2.0.11 which is the latest binary which was available in the repository earlier.  Newer releases will now be done through releases feature of Github.
