### ISSUE TITLE
Maintenance and further development

### ISSUE THREAD

**Issue by silkentrance** [tusharvjoshi/NBDrupalDevel#41]
Are there any plans on maintaining or even further developing this in the future?

I already tried to contact you via mail but until today there was no reply to that.

**Comment by HollyIT** [comment]
I'm no longer maintaining this project, as I switched over to PHPStorm a couple of years ago and simply don't have the time. If anyone is interested in adopting it, please let me know and I can transfer ownership.

**Comment by tusharvjoshi** [comment]
I am currently connected to NetBeans plugin development as well as Drupal modules and themes development.  I would take a look into the current issues

**Comment by tusharvjoshi** [comment]
@HollyIT Hi Jamie, how do you want to shift the maintenance to someone else?  Should I fork and update my own copy or you will add me as a contributor to this project for maintenance?  Will  you need some actions to be done before you decide who can take up the project? Please share your views.

**Comment by HollyIT** [comment]
If you want to take it over, I can transfer the ownership of the repository to you inside Github, so that you have full control over it.

**Comment by tusharvjoshi** [comment]
Ok, fine.  Please transfer the ownership of repository inside Github to my user that is tusharvjoshi
I will start by updating the plugin for NetBeans 8.2 recent release.

**Comment by HollyIT** [comment]
Hmmm, it won't let me transfer it since you have a fork. "tusharvjoshi/NBDrupalDevel already exists" My guess is you would have to delete that and then I can try again. Until then I added you in as a collaborator, so you can do commits and that.

**Comment by tusharvjoshi** [comment]
Oh ok, I have deleted my fork now.  Please check now.

**Comment by HollyIT** [comment]
It took it that time. I believe you'll get an email to confirm on your end.

**Comment by tusharvjoshi** [comment]
Thanks for the quick response. @silkentrance I will be looking into this plugin over this weekend, and will be considering any updates for the current scenario of Drupal 8 development updates for this plugin.

**Comment by silkentrance** [comment]
Well, now, I was actually applying myself for that... Regardless, since @tusharvjoshi took over the project, lets make the best of it :smile: and hopefully we get things rolling again.
