### ISSUE TITLE
Name change

### ISSUE THREAD

**Issue by silkentrance** [tusharvjoshi/NBDrupalDevel#42]
Personally, I think that the name NBDrupalDevelopmentTool is rather long and that NDDT is a working, yet rather unpleasant acronym.

What do you think?

How about
- netbeans-php-drupal (repository, github project)
- php/drupal instead of php/drupaldevel (source, see official repository layout over at netbeans, all php related products/components have the php. prefix, e.g. php.symfony and so on)
- Drupal (plugin name, see symfony plugin bundle)

**Comment by tusharjoshi** [comment]
All these suggestions make sense.  I will check how these suggestions can be implemented in the current code base.
1. Project name - will need a project name (as well as url) change from Github settings
2. php.drupal - will need a package change which is just another push
3. Drupal plugin name - will be a change in the NetBeans module name which is just a properties file change and xml file change so will be quick from code change.

Will start doing changes #2 and #3 from the develop branch now
