### ISSUE TITLE
Unable to compile under NetBeans 8.1 Patch 1

### ISSUE THREAD

**Issue by silkentrance** [tusharvjoshi/NBDrupalDevel#47]
When trying to compile this, I get (develop branch)

```
warning: had to upgrade dependencies for module org.netbeans.modules.php.drupal: added = [module org.netbeans.api.templates > 1.0, module org.netbeans.modules.projectuiapi.base/1 > 1.78.0, module org.openide.filesystems.nb, module org.openide.filesystems.compat8, module org.netbeans.modules.editor.document > 1.0] removed = []; details: [Separate projectuiapi into desktop and NetBeans independent and dependent parts, Separation of desktop and cleanup, Templates API has been separated into its own module., The old editor settings and completion APIs have been deprecated, see http://wiki.netbeans.org/EditorSettingsUpgrade and update your module.]
/home/xxx/netbeans-8.1/harness/build.xml:174: Cannot compile against a module: /home/xxx/netbeans-8.1/platform/lib/org-openide-util-ui.jar because of dependency: org.openide.util.ui > 9.6.1 found 9.4.1
BUILD FAILED (total time: 1 second)
```

See http://wiki.netbeans.org/EditorSettingsUpgrade.

@tusharvjoshi What version of NetBeans are you using?

**Comment by silkentrance** [comment]
I was able to resolve the problem by changing the version for that component to the implementation version and not the specification version, however, out of the box, the plugin does not compile, so the problem persists, along with the missing/upgraded dependencies.

**Comment by tusharjoshi** [comment]
@silkentrance I am compiling develop branch using latest NetBeans 8.2 build.  NetBeans 8.2 is released and available on NetBeans site download page.  It is advisable to use NetBeans 8.2 for releases from here onwards.

There is a plugin dependency change for Utilities API in NetBeans 8.2 which was committed hence this branch will not build out of box in any version less tan NetBeans 8.2

**Comment by silkentrance** [comment]
@tusharvjoshi thank you for the information.I will upgrade my dev env asap.
